check_interval: 60  # сек

telegram_alerts: true
webhooks: false

targets:
  - name: Main-Burdela
    type: ping
    host: 192.168.0.182

  - name: Gringo-Burdela
    type: http
    url: http://192.168.0.179/

webhooks:
  - url: "https://webhook.site/your-unique-url"
    payload:
      target: "{name}"
      status: "{status}"
      host: "{host}"
      timestamp: "{timestamp}"
      type: "{type}"


  